build:
  image: node:5
  commands:
    - npm i
    - pwd
    - ./node_modules/bower/bin/bower install --allow-root
    - ./node_modules/gulp/bin/gulp.js build

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    username: 'drone'
    channel: '#code'
    on_started: true
    on_success: true
    on_failure: true

# build:
#   image: node:5
#   commands:
#     - pwd
#     - npm i -g -q node-gyp
#     - npm i -g -q coffee-script
#     - npm i -g -q gulp
#     - npm i -g -q bower
#     - bower install --allow-root
#     - which gulp
#     - gulp build

# deploy:
#   bash:
#     script:
#       - ./drone/deploy.sh

# deploy:
#   rsync:
#     host: 45.55.237.204
#     user: root
#     port: 22
#     source: static_generated
#     target: /var/www/afaa.hyprtxt.com/static_generated
#     recursive: true
#     delete: true

# deploy:
#   ssh:
#     host: 45.55.237.204
#     user: root
#     port: 22
#     commands:
#       - source /root/.bashrc
#       - echo 'source done'
#       - cd /var/www/afaa.hyprtxt.com
#       - pwd
#       - whoami
#       - git pull
#       - npm -q i
#       - bower install --allow-root
#       - gulp build
