build:
  image: node:5
  commands:
    - npm -q -g i gulp bower
    - npm -q i
    - bower install --allow-root
    - gulp build

notify:
  hipchat:
    room: Sitefinity
    token: vE1iFkfmQUL9FtiqWBFoOtLnOkVO3dfvgKS3D2r4
    on_started: true
    on_success: true
    on_failure: true
