build:
  image: node:5
  commands:
    - npm -q -g i gulp bower node-gyp
    - npm -q i
    - bower install --allow-root
    - gulp build

# deploy:
#   bash:
#     script:
#       - ./drone/deploy.sh

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    username: 'drone'
    channel: '#code'
    on_started: true
    on_success: true
    on_failure: true
