kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: build
    image: node:dubnium-alpine3.10
    commands:
      - yarn
      - yarn run bower
      - yarn run build
  - name: stage
    image: alpine
    volumes:
      - name: nginx
        path: /drone/src/nginx
    commands:
      - cp -r static_generated nginx/stage
  - name: deploy
    image: alpine
    volumes:
      - name: nginx
        path: /drone/src/nginx
    commands:
      - rm -r nginx/previous
      - mv nginx/public nginx/previous
      - mv nginx/stage nginx/public
    when:
      branch:
        - main
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache/afaa.hyprtxt.dev
  - name: nginx
    host:
      path: /var/www/afaa.hyprtxt.dev
