build:
  image: node:5
  commands:
    - which git
    - which node
    - npm -q -g i gulp bower
    - npm -q i
    - bower install --allow-root
    - gulp build

notify:
  email:
    recipients:
      - taylor@hyprtxt.com
